name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - flutterflow # Replace with your branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Flutter
      - name: Install Flutter
        run: |
          git clone https://github.com/flutter/flutter.git --depth 1 -b stable /usr/local/flutter
          echo "::add-path::/usr/local/flutter/bin"
          flutter --version

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build the Flutter web project
      - name: Build Flutter web
        run: flutter build web --release

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
