name: Deploy Flutter Web to GitHub Pages

on:
  push:
    branches:
      - flutterflow # Replace with your branch name if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Flutter using a prebuilt action
      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.0" # Specify an exact Flutter version

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Build the Flutter web project
      - name: Build Flutter web
        run: flutter build web --release

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build/web
